import type { ChampionBlueprint, CombatUnit } from './types';

const blueTeam: ChampionBlueprint[] = [
  {
    id: 'blue-garen',
    name: '가렌',
    title: '데마시아의 힘',
    role: 'Vanguard',
    team: 'blue',
    maxHp: 98,
    speed: 55,
    accent: '#d6b35f',
    abilities: [
      {
        id: 'decisive-strike',
        name: '결정타',
        description: '안정적으로 선공을 여는 일격입니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 18 }],
      },
      {
        id: 'courage',
        name: '용기',
        description: '다음 교전에 대비해 단단한 보호막을 얻습니다.',
        cooldown: 2,
        targetType: 'self',
        effects: [{ kind: 'shield', amount: 22 }],
      },
      {
        id: 'judgment',
        name: '심판',
        description: '회전하며 적 전열 전체를 베어 냅니다.',
        cooldown: 3,
        targetType: 'all-enemies',
        effects: [{ kind: 'damage', amount: 12 }],
      },
    ],
  },
  {
    id: 'blue-ahri',
    name: '아리',
    title: '구미호',
    role: 'Mage',
    team: 'blue',
    maxHp: 78,
    speed: 68,
    accent: '#ec8d8d',
    abilities: [
      {
        id: 'orb-of-deception',
        name: '현혹의 구슬',
        description: '안정적인 원거리 폭딜입니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 17 }],
      },
      {
        id: 'charm',
        name: '매혹',
        description: '단일 적을 묶어 두는 제어기입니다.',
        cooldown: 3,
        targetType: 'enemy',
        effects: [
          { kind: 'damage', amount: 10 },
          { kind: 'stun', turns: 1 },
        ],
      },
      {
        id: 'spirit-rush',
        name: '혼령 질주',
        description: '강한 마법 피해를 터뜨립니다.',
        cooldown: 3,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 25 }],
      },
    ],
  },
  {
    id: 'blue-jinx',
    name: '징크스',
    title: '난폭한 말괄량이',
    role: 'Marksman',
    team: 'blue',
    maxHp: 74,
    speed: 72,
    accent: '#6dd7d0',
    abilities: [
      {
        id: 'zap',
        name: '빠직!',
        description: '먼 거리에서 찌르는 견제기입니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 15 }],
      },
      {
        id: 'flame-chompers',
        name: '와작와작 뻥!',
        description: '적 하나의 움직임을 끊어 냅니다.',
        cooldown: 2,
        targetType: 'enemy',
        effects: [
          { kind: 'damage', amount: 8 },
          { kind: 'stun', turns: 1 },
        ],
      },
      {
        id: 'super-mega-death-rocket',
        name: '초강력 초토화 로켓!',
        description: '적 전체에게 폭발 피해를 줍니다.',
        cooldown: 4,
        targetType: 'all-enemies',
        effects: [{ kind: 'damage', amount: 14 }],
      },
    ],
  },
];

const redTeam: ChampionBlueprint[] = [
  {
    id: 'red-darius',
    name: '다리우스',
    title: '녹서스의 실력자',
    role: 'Vanguard',
    team: 'red',
    maxHp: 102,
    speed: 52,
    accent: '#d97d59',
    abilities: [
      {
        id: 'crippling-strike',
        name: '마비의 일격',
        description: '단일 적에게 무거운 도끼를 내리칩니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 18 }],
      },
      {
        id: 'defy',
        name: '응수',
        description: '들어올 피해에 대비해 몸을 단단히 세웁니다.',
        cooldown: 2,
        targetType: 'self',
        effects: [{ kind: 'shield', amount: 20 }],
      },
      {
        id: 'noxian-guillotine',
        name: '녹서스의 단두대',
        description: '약해진 적을 마무리하는 강한 일격입니다.',
        cooldown: 3,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 28 }],
      },
    ],
  },
  {
    id: 'red-annie',
    name: '애니',
    title: '어둠의 아이',
    role: 'Mage',
    team: 'red',
    maxHp: 76,
    speed: 66,
    accent: '#f0b35f',
    abilities: [
      {
        id: 'disintegrate',
        name: '붕괴',
        description: '직접 꽂아 넣는 마법 폭딜입니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 16 }],
      },
      {
        id: 'molten-shield',
        name: '용암 방패',
        description: '다음 교환을 위해 자신을 보호합니다.',
        cooldown: 2,
        targetType: 'self',
        effects: [{ kind: 'shield', amount: 18 }],
      },
      {
        id: 'summon-tibbers',
        name: '티버 소환',
        description: '적 전체에 광역 피해를 줍니다.',
        cooldown: 4,
        targetType: 'all-enemies',
        effects: [{ kind: 'damage', amount: 13 }],
      },
    ],
  },
  {
    id: 'red-caitlyn',
    name: '케이틀린',
    title: '필트오버의 보안관',
    role: 'Marksman',
    team: 'red',
    maxHp: 72,
    speed: 70,
    accent: '#9ab3e6',
    abilities: [
      {
        id: 'piltover-peacemaker',
        name: '필트오버 피스메이커',
        description: '정밀한 소총 사격을 가합니다.',
        cooldown: 1,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 18 }],
      },
      {
        id: 'yordle-snap-trap',
        name: '요들잡이 덫',
        description: '노출된 적을 붙잡아 둡니다.',
        cooldown: 2,
        targetType: 'enemy',
        effects: [
          { kind: 'damage', amount: 9 },
          { kind: 'stun', turns: 1 },
        ],
      },
      {
        id: 'ace-in-the-hole',
        name: '비장의 한 발',
        description: '단일 적을 노리는 강력한 마무리 기술입니다.',
        cooldown: 3,
        targetType: 'enemy',
        effects: [{ kind: 'damage', amount: 25 }],
      },
    ],
  },
];

export function createInitialUnits(): CombatUnit[] {
  return [...blueTeam, ...redTeam].map((blueprint) => ({
    ...blueprint,
    hp: blueprint.maxHp,
    shield: 0,
    stunTurns: 0,
    cooldowns: Object.fromEntries(
      blueprint.abilities.map((ability) => [ability.id, 0]),
    ),
  }));
}
